TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of DB files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
#  Creation of <name>.dbd file from <name>Include.dbd
#DBDNAME += HP53181A.dbd
#----------------------------------------------------
# Add databases, templates, substitutions like this
DB += Hp3458A.proto.db
DB += Hp3458A.stream.db
#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += HP3458A.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
