TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of DB files using dbst (DEFAULT: NO)
#DB_OPT = YES
#----------------------------------------------------
# Add databases, templates, substitutions like this
# Install .db files
DB += Hp3458A.db
#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += Hp3458A.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
